import json
import logging
from pathlib import Path

from modelica_builder.modelica_mos_file import ModelicaMOS

logger = logging.getLogger(__name__)


def _build_default_loop_order(sys_param_data: dict) -> list | None:
    """Build a conservative default loop-order structure from system params.

    This fallback is used only when _loop_order.json is missing.
    """
    fg = sys_param_data.get("district_system", {}).get("fifth_generation")
    if not fg:
        return None

    buildings = sys_param_data.get("buildings", [])
    bldg_ids = [b.get("geojson_id") for b in buildings if b.get("geojson_id")]
    if not bldg_ids:
        return None

    loop_group = {"list_bldg_ids_in_group": bldg_ids}

    borefields = fg.get("ghe_parameters", {}).get("borefields", [])
    ghe_ids = [b.get("ghe_id") for b in borefields if b.get("ghe_id")]
    if ghe_ids:
        loop_group["list_ghe_ids_in_group"] = [ghe_ids[0]]

    heat_sources = fg.get("heat_source_parameters", [])
    source_ids = [s.get("heat_source_id") for s in heat_sources if s.get("heat_source_id")]
    if source_ids:
        loop_group["list_source_ids_in_group"] = [source_ids[0]]

    return [loop_group]


def load_loop_order(system_parameters_file: Path) -> list:
    """Loads the loop order from a JSON file

    loop_order file is always saved next to the system parameters file

    :param system_parameters_file: Path to the system parameters file
    :return: list of building & ghe ids in loop order
    """
    loop_order_path = Path(system_parameters_file).parent / "_loop_order.json"
    if not loop_order_path.is_file():
        sys_param_data = json.loads(Path(system_parameters_file).read_text())
        default_loop_order = _build_default_loop_order(sys_param_data)
        if default_loop_order is None:
            raise FileNotFoundError(f"Loop order file not found at {loop_order_path}")
        loop_order_path.write_text(json.dumps(default_loop_order, indent=2))
        logger.warning(
            "Loop order file was missing. Wrote default loop-order structure to %s",
            loop_order_path,
        )
        return default_loop_order
    return json.loads(loop_order_path.read_text())


def get_num_buildings_in_loop_order(loop_order: list) -> int:
    """
    Calculate the number of buildings in the loop order.
    Needed because system params file can have buildings that are not in the thermal network.
    :param loop_order: List of loop order dicts generated by ThermalNetwork
    :return: Number of buildings in the loop order
    """
    num_buildings = 0
    for group in loop_order:
        num_buildings += len(group.get("list_bldg_ids_in_group", []))
    return num_buildings


def set_loop_order_data_in_template_params(
    template_params: dict, feature_properties: list[dict], loop_order: list
) -> dict:
    """
    Set the loop order data in the template parameters dictionary.

    :param template_params: Dictionary of template parameters
    :param feature_properties: List of feature property dicts from the GeoJSON
    :param loop_order: List of loop order dicts generated by ThermalNetwork
    :return: Updated template parameters dictionary with loop order data
    """
    # determine total number of sources and GHEs
    number_of_sources = 0
    for group in loop_order:
        sources = group.get("list_source_ids_in_group", [])
        ghes = group.get("list_ghe_ids_in_group", [])
        number_of_sources += len(sources) + len(ghes)

    template_params["loop_order"] = {
        "number_of_loops": len(loop_order),
        "data": loop_order,
        "number_of_sources": number_of_sources,
    }

    dict_of_pipe_lengths = {
        feature_prop.get("startFeatureId"): feature_prop["total_length"]
        for feature_prop in feature_properties
        if feature_prop["type"] == "ThermalConnector"
    }

    ordered_feature_list = []
    ordered_pipe_list = []
    for loop in loop_order:
        ordered_feature_list.extend(loop["list_bldg_ids_in_group"])
        if "list_ghe_ids_in_group" in loop:
            ordered_feature_list.extend(loop["list_ghe_ids_in_group"])
        if "list_source_ids_in_group" in loop:
            ordered_feature_list.extend(loop["list_source_ids_in_group"])

    for feature in ordered_feature_list:
        pipe_length = dict_of_pipe_lengths.get(feature)
        if pipe_length is not None:
            ordered_pipe_list.append(pipe_length)

    if ordered_pipe_list:
        template_params["globals"]["lDis"] = str(ordered_pipe_list[:-1]).replace("[", "{").replace("]", "}")
        template_params["globals"]["lEnd"] = ordered_pipe_list[-1]
    else:
        logger.warning("No thermal connector lengths matched loop-order features; using zero-length lDis and lEnd=0.")
        ldis_count = max(get_num_buildings_in_loop_order(loop_order) - 1, 0)
        template_params["globals"]["lDis"] = f"fill(0, {ldis_count})"
        template_params["globals"]["lEnd"] = 0
    return template_params


def set_minimum_dhw_load(data_dir) -> None:
    """
    If peak water heating load is 0, set it to 5kW or 10% of peak space heating load, whichever is greater.

    :param data_dir: Path to the Modelica data directory
    :return: None
    """
    if data_dir.is_dir():
        for bldg_dir in data_dir.iterdir():
            mo_load_file = data_dir / bldg_dir / "modelica.mos"
            # In case the modelica loads file isn't named modelica.mos:
            if not mo_load_file.is_file():
                modelica_loads = list((data_dir / bldg_dir).rglob("*"))
                if len(modelica_loads) == 1:
                    mo_load_file = modelica_loads[0]
            if mo_load_file.is_file():
                mos_file = ModelicaMOS(mo_load_file)
                # Force peak water heating load to be at least 5000W
                peak_water = mos_file.retrieve_header_variable_value("Peak water heating load", cast_type=float)
                if peak_water == 0:
                    peak_heat = mos_file.retrieve_header_variable_value("Peak space heating load", cast_type=float)
                    peak_swh = max(peak_heat / 10, 5000)

                    mos_file.replace_header_variable_value("Peak water heating load", peak_swh)
                    mos_file.save()
    else:
        # The scaffold didn't get built properly or there are no loads in the Modelica package.
        logger.warning(
            f"Could not find Modelica data directory {data_dir}. Perhaps there are no loads in the model,"
            " and perhaps that is intentional."
        )
