name: Documentation

on:
  push:

permissions:
  contents: write

jobs:
  test-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - name: Install documentation dependencies
        run: pip install -r docs/docs_requirements.txt
      - name: Build documentation
        run: mkdocs build --strict

  deploy:
    runs-on: ubuntu-latest
    needs: test-docs
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment:
      name: github-pages
    steps:
      - uses: actions/checkout@v6
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: https://docs.urbanopt.net/geojson-modelica-translator/
          REQUIREMENTS: docs/docs_requirements.txt
